# 这是你的 Hugo 博客配置文件
baseURL = 'https://dontsupportvectormachine.github.io/'
title = '我的新博客'
theme = 'PaperMod' # 确保与你安装的主题文件夹名一致
locale = 'zh-cn'

[params]
  homeInfoParams:
    Title: "Hi there 👋"
    Content: "欢迎来到我的博客，这里记录了我的学习与思考。"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 10

[[menu.main]]
  identifier = "categories"
  name = "分类"
  url = "/categories/"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 30