baseURL = 'https://dontsupportvectormachine.github.io/'
title = '我的新博客'
theme = 'Stack'
locale = 'zh-cn'
paginate = 5

# 主题基础设置
[params]
  # 侧边栏头像
  sidebar.avatar = '/img/avatar.png'   # 需要你准备一张头像图片放在 static/img/avatar.png
  # 副标题
  sidebar.subtitle = '记录我的学习生涯'
  # 文章列表显示摘要与否
  article.excerpt = true
  # 代码高亮
  highlight.highlightStyle = 'github-dark'
  # 保证首页地址不出错
  mainSections = ["posts"]

# 主菜单
[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 2

[[menu.main]]
  identifier = "categories"
  name = "分类"
  url = "/categories/"
  weight = 3

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 4

# 友情链接（可选）
[[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/DontSupportVectorMachine"
  weight = 1